export const ADD_RECIPES = "ADD_RECIPES"
export const ADD_DIETTYPE = "ADD_DIETTYPE"
export const ADD_DIET = "ADD_DIET"
export const ADD_POSTED = "ADD_POSTED"
export const ADD_FILTERED = "ADD_FILTERED"
export const ADD_RECIPE = "ADD_RECIPE"
export const ADD_MESSAGE = "ADD_MESSAGE"
export const RESET_MESSAGE= "RESET_MESSAGE"